# version: "3.8"

services:
    app:
        build:
            context: .
        image: expense_tracker_app
        container_name: expense_tracker_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: expense_tracker_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    node:
        image: node:20
        container_name: expense_tracker_node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173" # For Vite dev server
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: expense_tracker_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: expense_tracker
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3310:3306"
        volumes:
            - expense_tracker_db:/var/lib/mysql

volumes:
    expense_tracker_db:
